return {
    Tiles = {
        Hospital = {
            Name = "Residency Hospital",
            PlaceId = 000,
            MaxPlayers = 100,
            Image = { -- Picks a random image
                "rbxassetid://000"
            }
        },
        Security = {
            Name = "Security Training",
            PlaceId = 000,
            MaxPlayers = 100,
            Image = { -- Picks a random image
                "rbxassetid://000"
            }
        },
        Training = {
            Name = "Training Center",
            PlaceId = 000,
            MaxPlayers = 100,
            Image = { -- Picks a random image
                "rbxassetid://000"
            }
        },
        Interview = {
            Name = "Interview Center",
            PlaceId = 000,
            MaxPlayers = 100,
            Image = { -- Picks a random image
                "rbxassetid://000"
            }
        },
    },
    HubBypass = {
        337922098, -- NocturnalStory
        542336613, -- dan_kulik
        5557366, -- blaadam
    }
}