return {
	Tiles = {
		Hospital = {
			Name = "Hospital",
			PlaceId = 18344702548,
			MaxPlayers = 100,
			Image = { -- Picks a random image
				"rbxassetid://000",
			},
		},
		ResidencyHospital = {
			Name = "Residency Hospital",
			PlaceId = 000,
			MaxPlayers = 100,
			Image = { -- Picks a random image
				"rbxassetid://17801433194",
			},
		},
		SecurityTraining = {
			Name = "Security Training",
			PlaceId = 000,
			MaxPlayers = 100,
			Image = { -- Picks a random image
				"rbxassetid://17801434486",
			},
		},
		TrainingCenter = {
			Name = "Training Center",
			PlaceId = 000,
			MaxPlayers = 100,
			Image = { -- Picks a random image
				"rbxassetid://17801387396",
			},
		},
		InterviewCenter = {
			Name = "Interview Center",
			PlaceId = 000,
			MaxPlayers = 100,
			Image = { -- Picks a random image
				"rbxassetid://17801335060",
			},
		},
	},
	LimitedDealData = {
		GamepassID = 93578829,
		OldCost = 0,
	},
	Gamepasses = {
		703120436, -- Registered Nurse
		703084504, -- Nurses in Charge
		702989525, -- Doctors Assistant
		703492010, -- Medical Doctor
		704109702, -- Surgeon
		702631689, -- Head of Doctors
		769368925, -- NPC Access
		8342994, -- VIP
		8342996, -- Wheelchair
		93578829, -- Maintenance Team
		93579314, -- Janitorial Service
		93580458, -- Balloon
		93603480, -- Lobby Piano
		93625105, -- Double Credits
	},
	HubBypass = {
		337922098, -- NocturnalStory
		542336613, -- dan_kulik
		5557366, -- blaadam
	},
}
